# Generated by Django 4.2.7 on 2023-12-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0002_auctionlisting_comment_bid"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="category",
            field=models.CharField(default="Uncategorized", max_length=50),
        ),
    ]
