# Generated by Django 4.2.7 on 2023-12-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_auctionlisting_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
