# Generated by Django 4.2.7 on 2023-12-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_auctionlisting_is_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auctionlisting",
            name="image",
        ),
        migrations.AddField(
            model_name="auctionlisting",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
