# Generated by Django 4.2.7 on 2023-12-08 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0010_alter_watchlist_listing"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bid",
            old_name="bid_amount",
            new_name="amount",
        ),
        migrations.RenameField(
            model_name="bid",
            old_name="created_at",
            new_name="timestamp",
        ),
        migrations.AlterField(
            model_name="bid",
            name="bidder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="listing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.auctionlisting",
            ),
        ),
    ]
